"""i forgot

Revision ID: 269be9bbd6b5
Revises: cd69aaf00e38
Create Date: 2025-12-31 18:38:22.155079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269be9bbd6b5'
down_revision: Union[str, Sequence[str], None] = 'cd69aaf00e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_material_raw_material_id_fkey'), 'product_material', type_='foreignkey')
    op.drop_constraint(op.f('product_material_product_id_fkey'), 'product_material', type_='foreignkey')
    op.create_foreign_key(None, 'product_material', 'raw_materials', ['raw_material_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_material', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_material', type_='foreignkey')
    op.drop_constraint(None, 'product_material', type_='foreignkey')
    op.create_foreign_key(op.f('product_material_product_id_fkey'), 'product_material', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_material_raw_material_id_fkey'), 'product_material', 'raw_materials', ['raw_material_id'], ['id'])
    # ### end Alembic commands ###
