"""add_doc_payment_relation

Revision ID: 404c1eb56aff
Revises: c0e69f7a1cf2
Create Date: 2026-02-25 04:48:20.225417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404c1eb56aff'
down_revision: Union[str, Sequence[str], None] = 'c0e69f7a1cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
