"""add_format_to_items_products

Revision ID: 43fd3f826861
Revises: 404c1eb56aff
Create Date: 2026-03-05 05:26:01.902968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fd3f826861'
down_revision: Union[str, Sequence[str], None] = '404c1eb56aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PENDING_PAYMENT', 'PARTIAL_PAID', 'PAID', name='document_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.add_column('order_items', sa.Column('format', sa.Enum('SM72', 'SM74', 'GTO', name='product_format', native_enum=False), server_default=sa.text("'SM72'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'format')
    op.alter_column('documents', 'status',
               existing_type=sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'PENDING_PAYMENT', 'PARTIAL_PAID', 'PAID', name='document_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    # ### end Alembic commands ###
