"""add status to order items

Revision ID: 5822b3cf58a0
Revises: 8fb4b3c34115
Create Date: 2025-12-18 17:15:37.577279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5822b3cf58a0'
down_revision: Union[str, Sequence[str], None] = '8fb4b3c34115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'status')
    # ### end Alembic commands ###
