"""add_user_company_relation

Revision ID: 598e5321bb7e
Revises: 269be9bbd6b5
Create Date: 2026-01-08 13:54:16.578280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e5321bb7e'
down_revision: Union[str, Sequence[str], None] = '269be9bbd6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_created_by_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'created_by')
    op.add_column('users', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.add_column('companies', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('companies_created_by_fkey'), 'companies', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
