"""added foregin key to company

Revision ID: 67e620d8d37d
Revises: 5822b3cf58a0
Create Date: 2025-12-19 15:58:04.328418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e620d8d37d'
down_revision: Union[str, Sequence[str], None] = '5822b3cf58a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'created_by')
    # ### end Alembic commands ###
