"""add_finance_doc

Revision ID: 871bc0e4f599
Revises: af3a6c4c8eb9
Create Date: 2026-02-25 01:20:31.146782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871bc0e4f599'
down_revision: Union[str, Sequence[str], None] = 'af3a6c4c8eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_number', sa.String(length=20), server_default=sa.text("concat('#', lpad(nextval('document_number_seq')::text, 5, '0'))"), nullable=False),
    sa.Column('document_type', sa.Enum('DEVIS', 'FACTURE', name='document_type_enum', native_enum=False), server_default=sa.text("'DEVIS'"), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PENDING_PAYMENT', 'PARTIAL_PAID', 'PAID', name='document_status_enum', native_enum=False), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('total_ht', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('total_remaining', sa.Float(), nullable=False),
    sa.Column('devis_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
