"""added created by to orders

Revision ID: ca18369913a7
Revises: 67e620d8d37d
Create Date: 2025-12-20 15:52:47.592934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca18369913a7'
down_revision: Union[str, Sequence[str], None] = '67e620d8d37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'created_by')
    # ### end Alembic commands ###
