"""updated order and items

Revision ID: e224da1af1cc
Revises: 282017327c11
Create Date: 2025-12-29 19:38:00.341357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e224da1af1cc'
down_revision: Union[str, Sequence[str], None] = '282017327c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_id', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('item_number', sa.String(length=20), server_default=sa.text("concat('item#', lpad(nextval('item_number_seq')::text, 5, '0'))"), nullable=False))
    op.add_column('order_items', sa.Column('item_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_column('order_items', 'item_name')
    op.add_column('orders', sa.Column('order_number', sa.String(length=20), server_default=sa.text("concat('ORD#', lpad(nextval('order_number_seq')::text, 5, '0'))"), nullable=False))
    op.alter_column('orders', 'order_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_column('orders', 'order_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'order_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orders', 'order_number')
    op.add_column('order_items', sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item_price')
    op.drop_column('order_items', 'item_number')
    op.drop_column('order_items', 'product_id')
    # ### end Alembic commands ###
