"""add_company_order_relationship

Revision ID: e6a897a87d5b
Revises: a0d8872c5010
Create Date: 2026-02-17 08:57:05.440711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a897a87d5b'
down_revision: Union[str, Sequence[str], None] = 'a0d8872c5010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'company_id')
    # ### end Alembic commands ###
