"""added folder status

Revision ID: e862c5ed179b
Revises: eada99acd781
Create Date: 2025-12-17 18:49:41.316013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e862c5ed179b'
down_revision: Union[str, Sequence[str], None] = 'eada99acd781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('folder_status', sa.String(),server_default='PENDING', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'folder_status')
    # ### end Alembic commands ###
