"""add google drive folder id

Revision ID: eada99acd781
Revises: ba1c3b61cc3d
Create Date: 2025-12-16 15:26:26.656669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eada99acd781'
down_revision: Union[str, Sequence[str], None] = 'ba1c3b61cc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('drive_folder_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'drive_folder_id')
    # ### end Alembic commands ###
