from enum import StrEnum


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    IN_REVIEW = "IN_REVIEW"
    ACCEPTED = "ACCEPTED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY"
    DELIVERED = "DELIVRED"
    PAIED = "PAIED"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
