from enum import StrEnum


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PARTIAL_DELIVERED = "PARTIAL_DELIVERED"
    DELIVERED = "DELIEVRED"
    PARTIAL_PAIED = "PARTIAL_PAIED"
    PAIED = "PAIED"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
