from enum import StrEnum


class OrderItemStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WAIT_FOR_PROCESSING = "WAIT_FOR_PROCESSING:"
    PROCESSING = "PROCESSING"
    PRINTED = "PRINTED"
    PAIED = "PAIED"
    FINISHED = "FINISHED"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
