from enum import StrEnum


class Permissions(StrEnum):
    CAN_SEE_ALL = "CAN_SEE_ALL"
    CAN_CREATE_ALL = "CAN_CREATE_ALL"
    CAN_DELETE_ALL = "CAN_DELETE_ALL"
    CAN_UPDATE_ALL = "CAN_UDPATE_ALL"
    CAN_READ_ALL = "CAN_READ_ALL"

    CAN_READ_COMPANY = "CAN_READ_COMPANY"
    CAN_CREATE_COMPANY = "CAN_CREATE_COMPANY"
    CAN_UPDATE_COMPANY = "CAN_UPDATE_COMPANY"
    CAN_DELETE_COMPANY = "CAN_DELETE_COMPANY"
    CAN_LIST_COMPANY = "CAN_LIST_COMPANY"

    CAN_READ_ORDER = "CAN_READ_ORDER"
    CAN_LIST_ORDERS = "CAN_LIST_ORDERS"
    CAN_CREATE_ORDER = "CAN_CREATE_ORDER"
    CAN_UPDATE_ORDER = "CAN_UPDATE_ORDER"
    CAN_DELETE_ORDER = "CAN_DELETE_ORDER"

    CAN_READ_ITEM = "CAN_READ_ITEM"
    CAN_LIST_ITEMS = "CAN_LIST_ITEMS"
    CAN_CREATE_ITEM = "CAN_CREATE_ITEM"
    CAN_DELETE_ITEM = "CAN_DELETE_ITEM"
    CAN_UPDATE_ITEM = "CAN_UPDATE_ITEM"

    CAN_CREATE_PRODUCT = "CAN_CREATE_PRODUCT"
    CAN_LIST_PRODUCTS = "CAN_LIST_PRODUCTS"
    CAN_DELETE_PRODUCT = "CAN_DELETE_PRODUCT"
    CAN_UPDATE_PRODUCT = "CAN_UPDATE_PRODUCT"
    CAN_READ_PRODUCT = "CAN_READ_PRODUCT"

    CAN_CREATE_MATERIAL = "CAN_CREATE_MATERIAL"
    CAN_LIST_MATERIAL = "CAN_LIST_MATERIAL"
    CAN_DELETE_MATERIAL = "CAN_DELETE_MATERIAL"
    CAN_UPDATE_MATERIAL = "CAN_UPDATE_MATERIAL"
    CAN_READ_MATETRIAL = "CAN_READ_MATERIAL"

    CAN_LIST_USERS = "CAN_LIST_USERS"
    CAN_READ_USER = "CAN_READ_USER"
    CAN_UPDATE_USER = "CAN_UPDATE_USER"
    CAN_DELETE_USER = "CAN_DELETE_USER"
    CAN_CREATE_USER = "CAN_CREATE_USER"
